create table if not exists public.beach_comments (
  id bigint generated by default as identity primary key,
  beach_slug text not null,
  page_path text not null,
  name text not null check (char_length(name) between 2 and 60),
  message text not null check (char_length(message) between 3 and 1200),
  created_at timestamptz not null default now()
);

create index if not exists beach_comments_beach_slug_created_at_idx
  on public.beach_comments (beach_slug, created_at desc);

alter table public.beach_comments enable row level security;

drop policy if exists "Public read beach comments" on public.beach_comments;
create policy "Public read beach comments"
on public.beach_comments
for select
to anon, authenticated
using (true);

drop policy if exists "Public insert beach comments" on public.beach_comments;
create policy "Public insert beach comments"
on public.beach_comments
for insert
to anon, authenticated
with check (
  char_length(name) between 2 and 60
  and char_length(message) between 3 and 1200
  and beach_slug <> ''
  and page_path <> ''
);
